---
# tasks file for db
# tasks file for db
- name: Show info about environment
  debug:
    msg: "This host is in the {{ env }} environment."

- name: Change mongo config file
  template:
    src: mongodb.conf.j2
    dest: /etc/mongodb.conf
    mode: 0644
  notify: restart mongodb
